begin;
select no_plan();
select ok(not has_function_privilege('anon','api.confirm_current_onboarding_preview(text)','EXECUTE'),'Anonymous confirmation denied');
select ok(not has_function_privilege('service_role','api.confirm_current_onboarding_preview(text)','EXECUTE'),'Service role cannot confirm Owner preview');
select ok(has_function_privilege('authenticated','api.confirm_current_onboarding_preview(text)','EXECUTE'),'Owner confirmation enabled');
select ok((select relrowsecurity from pg_class where oid='core.onboarding_preview_receipts'::regclass),'Receipt RLS enabled');
select ok(not has_table_privilege('authenticated','core.onboarding_preview_receipts','SELECT'),'Direct receipt reads denied');
select ok(not has_table_privilege('authenticated','core.onboarding_preview_receipts','INSERT'),'Direct receipt writes denied');
insert into auth.users(id,email) values
 ('78000000-0000-4000-8000-000000000001','receipt-one@example.test'),
 ('78000000-0000-4000-8000-000000000002','receipt-two@example.test');
create temporary table receipt_test_owners as select auth_user_id,owner_id from core.owner_auth_bindings
 where auth_user_id in ('78000000-0000-4000-8000-000000000001','78000000-0000-4000-8000-000000000002');
set local role authenticated;
set local request.jwt.claims='{"role":"authenticated"}';
select is(api.confirm_current_onboarding_preview(repeat('a',64))->>'status','unauthenticated','Missing subject denied');
set local request.jwt.claims='{"role":"authenticated","sub":"78000000-0000-4000-8000-000000000001"}';
select is(api.confirm_current_onboarding_preview(repeat('a',64))->>'status','step_not_available','S1 cannot bypass review');
select is(api.claim_current_owner_handle('receipt-one',1)->>'status','success','Claim Handle');
select is(api.set_current_owner_primary_use_case('personal',2)->>'status','success','Choose guidance');
select is(api.save_current_owner_basic_identity('Receipt Owner',null,null,3)->>'status','success','Save Identity');
select is(api.save_current_owner_starter_composition('clean',null,4)->>'status','success','Save layout');
select is(api.advance_current_owner_relevant_first_job(5)->>'status','success','Reach S6');
select is(api.confirm_current_onboarding_preview(null)->>'status','invalid_snapshot','Null digest rejected');
select is(api.confirm_current_onboarding_preview('bad')->>'status','invalid_snapshot','Malformed digest rejected');
select is(api.confirm_current_onboarding_preview(repeat('a',64))->>'status','stale_preview','Forged digest rejected');
create temporary table receipt_ack as select api.confirm_current_onboarding_preview(api.resolve_current_onboarding_preview()->>'snapshot_hash') as ack;
select is((select ack->>'status' from receipt_ack),'success','Current preview explicitly confirmed');
select ok((select ack->>'receipt_id' ~ '^[0-9a-f-]{36}$' from receipt_ack),'Opaque receipt UUID returned');
select is((select ack->>'snapshot_hash' from receipt_ack),api.resolve_current_onboarding_preview()->>'snapshot_hash','Receipt binds exact current digest');
select ok((select (ack->>'expires_at')::timestamptz > clock_timestamp() from receipt_ack),'Receipt has future expiry');
select is(api.confirm_current_onboarding_preview(api.resolve_current_onboarding_preview()->>'snapshot_hash'),(select ack from receipt_ack),'Same fresh review reuses UUID and fixed expiry');
select is(api.confirm_current_onboarding_preview(repeat('b',64))->>'status','stale_preview','Stale tab cannot supersede valid receipt');
reset role;
select is((select count(*) from core.onboarding_preview_receipts where owner_id=(select owner_id from receipt_test_owners where auth_user_id='78000000-0000-4000-8000-000000000001')),1::bigint,'One receipt per Owner');
select is((select expires_at-issued_at from core.onboarding_preview_receipts where owner_id=(select owner_id from receipt_test_owners where auth_user_id='78000000-0000-4000-8000-000000000001')),interval '10 minutes','TTL fixed to ten minutes');
select is((select revision from core.owner_onboarding_progress where owner_id=(select owner_id from receipt_test_owners where auth_user_id='78000000-0000-4000-8000-000000000001')),6::bigint,'Confirmation does not change progress');
select ok((select onboarding_completed_at is null from core.owners where id=(select owner_id from receipt_test_owners where auth_user_id='78000000-0000-4000-8000-000000000001')),'Confirmation does not activate Identity');
select is((select count(*) from core.spill_item_identity_registry where owner_id=(select owner_id from receipt_test_owners where auth_user_id='78000000-0000-4000-8000-000000000001')),0::bigint,'Confirmation creates no Item');
set local role authenticated;
select is(api.save_current_owner_basic_identity('Changed Owner',null,null,1,6)->>'status','success','Edit Working at S6');
select is(api.confirm_current_onboarding_preview((select ack->>'snapshot_hash' from receipt_ack))->>'status','stale_preview','Saved content change invalidates old digest');
select isnt(api.confirm_current_onboarding_preview(api.resolve_current_onboarding_preview()->>'snapshot_hash')->>'receipt_id',(select ack->>'receipt_id' from receipt_ack),'New preview rotates receipt');
update receipt_ack set ack=api.confirm_current_onboarding_preview(api.resolve_current_onboarding_preview()->>'snapshot_hash');
reset role;
update core.onboarding_preview_receipts set issued_at=now()-interval '11 minutes',expires_at=now()-interval '1 minute'
 where owner_id=(select owner_id from receipt_test_owners where auth_user_id='78000000-0000-4000-8000-000000000001');
set local role authenticated;
select isnt(api.confirm_current_onboarding_preview(api.resolve_current_onboarding_preview()->>'snapshot_hash')->>'receipt_id',(select ack->>'receipt_id' from receipt_ack),'Expired confirmation rotates token');
set local request.jwt.claims='{"role":"authenticated","sub":"78000000-0000-4000-8000-000000000002"}';
select is(api.claim_current_owner_handle('receipt-two',1)->>'status','success','Other Handle');
select is(api.set_current_owner_primary_use_case('creator',2)->>'status','success','Other guidance');
select is(api.save_current_owner_basic_identity('Other Receipt Owner',null,null,3)->>'status','success','Other Identity');
select is(api.save_current_owner_starter_composition('clean',null,4)->>'status','success','Other layout');
select is(api.advance_current_owner_relevant_first_job(5)->>'status','success','Other S6');
select is(api.confirm_current_onboarding_preview((select ack->>'snapshot_hash' from receipt_ack))->>'status','stale_preview','Other Owner cannot reuse first Owner digest');
select is(api.confirm_current_onboarding_preview(api.resolve_current_onboarding_preview()->>'snapshot_hash')->>'status','success','Other Owner confirms own preview');
reset role;
select is((select count(*) from core.onboarding_preview_receipts where owner_id in (select owner_id from receipt_test_owners)),2::bigint,'Two isolated Owner receipts');
update core.owners set account_state='restricted' where id=(select owner_id from receipt_test_owners where auth_user_id='78000000-0000-4000-8000-000000000002');
set local role authenticated;
select is(api.confirm_current_onboarding_preview(repeat('a',64))->>'status','owner_not_eligible','Restricted Owner denied');
reset role;
update core.owners set account_state='active',onboarding_completed_at=now() where id=(select owner_id from receipt_test_owners where auth_user_id='78000000-0000-4000-8000-000000000002');
set local role authenticated;
select is(api.confirm_current_onboarding_preview(repeat('a',64))->>'status','owner_not_eligible','Completed Owner cannot mint onboarding receipt');
reset role;
select * from finish();
rollback;
