begin;
select no_plan();
select ok(not has_function_privilege('authenticated','api.publish_current_onboarding(uuid,text,text)','EXECUTE'),'Publish endpoint withheld until transport is ready');
select ok(not has_function_privilege('anon','api.publish_current_onboarding(uuid,text,text)','EXECUTE'),'Anonymous publication denied');
select ok(not has_function_privilege('service_role','api.publish_current_onboarding(uuid,text,text)','EXECUTE'),'No service-role Owner publish entry');
select ok(not has_table_privilege('authenticated','core.identity_publications','SELECT'),'Raw Identity publication remains private');
select ok(not has_table_privilege('authenticated','core.spill_item_publications','INSERT'),'Direct Item publication denied');
select ok(not has_table_privilege('authenticated','core.first_onboarding_publications','SELECT'),'Other Owner acknowledgments remain private');
select ok(not has_function_privilege('authenticated','core.resolve_onboarding_preview_snapshot()','EXECUTE'),'Raw preview helper remains private');
grant execute on function api.publish_current_onboarding(uuid,text,text) to authenticated;
insert into auth.users(id,email) values
 ('79000000-0000-4000-8000-000000000001','publication-one@example.test'),
 ('79000000-0000-4000-8000-000000000002','publication-two@example.test'),
 ('79000000-0000-4000-8000-000000000003','publication-three@example.test');
create temporary table publication_owners as select auth_user_id,owner_id from core.owner_auth_bindings
 where auth_user_id in ('79000000-0000-4000-8000-000000000001','79000000-0000-4000-8000-000000000002','79000000-0000-4000-8000-000000000003');
set local role authenticated;
set local request.jwt.claims='{"role":"authenticated"}';
select is(api.publish_current_onboarding(null,null,'identity_only')->>'status','unauthenticated','No subject cannot publish');
set local request.jwt.claims='{"role":"authenticated","sub":"79000000-0000-4000-8000-000000000001"}';
select is(api.publish_current_onboarding(null,null,'identity_only')->>'status','review_required','No receipt prevents first publication');
select is(api.claim_current_owner_handle('publication-one',1)->>'status','success','Claim first Handle');
select is(api.set_current_owner_primary_use_case('personal',2)->>'status','success','First guidance');
select is(api.save_current_owner_basic_identity('Published Owner','Saved biography',null,3)->>'status','success','First Identity');
select is(api.save_current_owner_starter_composition('clean',null,4)->>'status','success','First layout');
select is(api.save_current_owner_product_draft('https://example.test/first-product','Saved Product',null)->>'status','success','Retain Product');
select is(api.save_current_owner_resource_draft('menu',null,'Saved Menu',null)->>'status','success','Retain incomplete Resource');
select is(api.advance_current_owner_relevant_first_job(5)->>'status','success','Reach first preview');
create temporary table first_publish_review as select api.confirm_current_onboarding_preview(api.resolve_current_onboarding_preview()->>'snapshot_hash') as receipt;
select is(api.publish_current_onboarding((select (receipt->>'receipt_id')::uuid from first_publish_review),(select receipt->>'snapshot_hash' from first_publish_review),'unknown')->>'status','invalid_bundle','Explicit bundle required');
select is(api.publish_current_onboarding((select (receipt->>'receipt_id')::uuid from first_publish_review),(select receipt->>'snapshot_hash' from first_publish_review),'product')->>'status','item_preparation_pending','URL/title cannot replace Product primary image/marketplace model');
select is(api.publish_current_onboarding((select (receipt->>'receipt_id')::uuid from first_publish_review),(select receipt->>'snapshot_hash' from first_publish_review),'resource')->>'status','item_invalid','Invalid selected Resource cannot silently become Identity-only');
reset role;
select ok(not exists(select 1 from core.identity_publications where owner_id=(select owner_id from publication_owners where auth_user_id='79000000-0000-4000-8000-000000000001')),'Failed selection publishes no Identity');
select ok((select onboarding_completed_at is null from core.owners where id=(select owner_id from publication_owners where auth_user_id='79000000-0000-4000-8000-000000000001')),'Failed selection does not complete onboarding');
set local role authenticated;
create temporary table first_publish_ack as select api.publish_current_onboarding((select (receipt->>'receipt_id')::uuid from first_publish_review),(select receipt->>'snapshot_hash' from first_publish_review),'identity_only') as ack;
select is((select ack->>'status' from first_publish_ack),'success','Explicit Identity-only publication succeeds');
select is((select ack->>'identity_status' from first_publish_ack),'published','Identity success authoritative');
select is((select ack->'item_status' from first_publish_ack),'null'::jsonb,'No Item success claimed');
select is(api.resolve_current_owner_state()->>'status','active','First Identity publication is completion boundary');
select is(api.resolve_current_onboarding_preview()->>'status','onboarding_complete','Completed Owner does not repeat onboarding');
select is(api.publish_current_onboarding((select (receipt->>'receipt_id')::uuid from first_publish_review),(select receipt->>'snapshot_hash' from first_publish_review),'identity_only'),(select ack from first_publish_ack),'Exact duplicate intent returns original acknowledgment');
select is(api.publish_current_onboarding((select (receipt->>'receipt_id')::uuid from first_publish_review),(select receipt->>'snapshot_hash' from first_publish_review),'resource')->>'status','conflicting_intent','Retry cannot silently change selected bundle');
reset role;
select is((select count(*) from core.identity_publications where owner_id=(select owner_id from publication_owners where auth_user_id='79000000-0000-4000-8000-000000000001')),1::bigint,'Retry creates one Identity');
select throws_ok($$update core.first_onboarding_publications set bundle='resource' where owner_id=(select owner_id from publication_owners where auth_user_id='79000000-0000-4000-8000-000000000001')$$,'23514','First-publication acknowledgments are immutable.','Successful retry acknowledgment cannot be rewritten');
select throws_ok($$delete from core.first_onboarding_publications where owner_id=(select owner_id from publication_owners where auth_user_id='79000000-0000-4000-8000-000000000001')$$,'23514','First-publication acknowledgments are immutable.','First publication cannot be erased to republish another bundle');
select throws_ok($$truncate core.first_onboarding_publications$$,'23514','First-publication acknowledgments are immutable.','First-Publish history cannot be truncated');
select is((select count(*) from core.spill_item_publications where owner_id=(select owner_id from publication_owners where auth_user_id='79000000-0000-4000-8000-000000000001')),0::bigint,'Identity-only has no empty Spill');
select is((select snapshot->>'display_name' from core.identity_publications where owner_id=(select owner_id from publication_owners where auth_user_id='79000000-0000-4000-8000-000000000001')),'Published Owner','Exact acknowledged Identity snapshot');
select is((select revision from core.identity_working where owner_id=(select owner_id from publication_owners where auth_user_id='79000000-0000-4000-8000-000000000001')),1::bigint,'Working revision is preserved');
select is((select revision from core.owner_onboarding_progress where owner_id=(select owner_id from publication_owners where auth_user_id='79000000-0000-4000-8000-000000000001')),7::bigint,'Only successful publication advances completion revision');
select is((select title from core.product_drafts where owner_id=(select owner_id from publication_owners where auth_user_id='79000000-0000-4000-8000-000000000001')),'Saved Product','Unselected Product remains recoverable');
select is((select title from core.resource_drafts where owner_id=(select owner_id from publication_owners where auth_user_id='79000000-0000-4000-8000-000000000001')),'Saved Menu','Invalid Resource remains recoverable');
update core.onboarding_preview_receipts set issued_at=now()-interval '11 minutes',expires_at=now()-interval '1 minute'
 where owner_id=(select owner_id from publication_owners where auth_user_id='79000000-0000-4000-8000-000000000001');
set local role authenticated;
select is(api.publish_current_onboarding((select (receipt->>'receipt_id')::uuid from first_publish_review),(select receipt->>'snapshot_hash' from first_publish_review),'identity_only'),(select ack from first_publish_ack),'Successful retry survives review expiry');
set local request.jwt.claims='{"role":"authenticated","sub":"79000000-0000-4000-8000-000000000002"}';
select is(api.publish_current_onboarding((select (receipt->>'receipt_id')::uuid from first_publish_review),(select receipt->>'snapshot_hash' from first_publish_review),'identity_only')->>'status','review_required','Foreign receipt grants no authority');
select is(api.claim_current_owner_handle('publication-two',1)->>'status','success','Second Handle');
select is(api.set_current_owner_primary_use_case('business',2)->>'status','success','Second guidance');
select is(api.save_current_owner_basic_identity('Resource Publisher',null,null,3)->>'status','success','Second Identity');
select is(api.save_current_owner_starter_composition('business',null,4)->>'status','success','Second layout');
select is(api.save_current_owner_resource_draft('menu','https://example.test/publish-menu','Published Menu',null)->>'status','success','Save full Resource');
select is(api.advance_current_owner_relevant_first_job(5)->>'status','success','Second preview');
create temporary table resource_publish_review as select api.confirm_current_onboarding_preview(api.resolve_current_onboarding_preview()->>'snapshot_hash') as receipt;
select is(api.publish_current_onboarding((select (receipt->>'receipt_id')::uuid from resource_publish_review),(select receipt->>'snapshot_hash' from resource_publish_review),'resource')->>'status','item_invalid','Pending source cannot publish');
reset role;
insert into core.external_destination_safety(normalized_url,url_hash,safety_status,scanner_version,checked_at,expires_at)
 values('https://example.test/publish-menu',encode(extensions.digest('https://example.test/publish-menu','sha256'),'hex'),'safe','publication-test',now()-interval '1 minute',now()+interval '1 microsecond');
set local role authenticated;
update resource_publish_review set receipt=api.confirm_current_onboarding_preview(api.resolve_current_onboarding_preview()->>'snapshot_hash');
select is(api.resolve_current_onboarding_preview()->'resource_draft'->'safety'->>'status','safe','Snapshot uses transaction time at TTL boundary');
select is(api.publish_current_onboarding((select (receipt->>'receipt_id')::uuid from resource_publish_review),(select receipt->>'snapshot_hash' from resource_publish_review),'resource')->>'status','item_invalid','Fresh wall-clock Publish check rejects expired verdict even when transaction snapshot says safe');
reset role;
update core.external_destination_safety set expires_at=now()+interval '1 hour' where normalized_url='https://example.test/publish-menu';
set local role authenticated;
update resource_publish_review set receipt=api.confirm_current_onboarding_preview(api.resolve_current_onboarding_preview()->>'snapshot_hash');
select is(api.save_current_owner_resource_draft('menu','https://example.test/publish-menu','Changed Menu',1)->>'status','success','Change acknowledged Working before Publish');
select is(api.publish_current_onboarding((select (receipt->>'receipt_id')::uuid from resource_publish_review),(select receipt->>'snapshot_hash' from resource_publish_review),'resource')->>'status','stale_preview','Stale review cannot publish changed Working');
update resource_publish_review set receipt=api.confirm_current_onboarding_preview(api.resolve_current_onboarding_preview()->>'snapshot_hash');
reset role;
create function pg_temp.reject_test_item_publication() returns trigger language plpgsql as $$
begin raise exception 'Synthetic Item publication failure'; end; $$;
create trigger synthetic_publication_failure before insert on core.spill_item_publications for each row execute function pg_temp.reject_test_item_publication();
set local role authenticated;
select throws_ok(format('select api.publish_current_onboarding(%L::uuid,%L,''resource'')',
 (select receipt->>'receipt_id' from resource_publish_review),(select receipt->>'snapshot_hash' from resource_publish_review)),
 'P0001','Synthetic Item publication failure','Item persistence failure rolls back entire bundle');
reset role;
select ok(not exists(select 1 from core.identity_publications where owner_id=(select owner_id from publication_owners where auth_user_id='79000000-0000-4000-8000-000000000002')),'No partial Identity after injected Item failure');
select ok((select onboarding_completed_at is null from core.owners where id=(select owner_id from publication_owners where auth_user_id='79000000-0000-4000-8000-000000000002')),'Injected failure does not complete onboarding');
drop trigger synthetic_publication_failure on core.spill_item_publications;
set local role authenticated;
create temporary table resource_publish_ack as select api.publish_current_onboarding((select (receipt->>'receipt_id')::uuid from resource_publish_review),(select receipt->>'snapshot_hash' from resource_publish_review),'resource') as ack;
select is((select ack->>'status' from resource_publish_ack),'success','Valid Resource bundle commits');
select is((select ack->>'item_status' from resource_publish_ack),'published','Resource status authoritative');
select is((select ack->>'spill_reference' from resource_publish_ack),'1','Existing reservation reused');
select is(api.publish_current_onboarding((select (receipt->>'receipt_id')::uuid from resource_publish_review),(select receipt->>'snapshot_hash' from resource_publish_review),'resource'),(select ack from resource_publish_ack),'Resource retry is idempotent');
reset role;
select is((select snapshot->>'title' from core.spill_item_publications where owner_id=(select owner_id from publication_owners where auth_user_id='79000000-0000-4000-8000-000000000002')),'Changed Menu','Only explicitly reviewed new revision published');
select is((select working_revision from core.spill_item_publications where owner_id=(select owner_id from publication_owners where auth_user_id='79000000-0000-4000-8000-000000000002')),2::bigint,'Published snapshot has exact Working revision');
select is((select count(*) from core.spill_item_identity_registry where owner_id=(select owner_id from publication_owners where auth_user_id='79000000-0000-4000-8000-000000000002')),1::bigint,'Publish/retry allocates no extra reference');
select is((select revision from core.resource_drafts where owner_id=(select owner_id from publication_owners where auth_user_id='79000000-0000-4000-8000-000000000002')),2::bigint,'Resource Working preserved');
update core.owners set account_state='restricted' where id=(select owner_id from publication_owners where auth_user_id='79000000-0000-4000-8000-000000000002');
set local role authenticated;
select is(api.publish_current_onboarding((select (receipt->>'receipt_id')::uuid from resource_publish_review),(select receipt->>'snapshot_hash' from resource_publish_review),'resource')->>'status','owner_not_eligible','Current restriction takes precedence over successful retry');
reset role;
update core.owners set onboarding_completed_at=now() where id=(select owner_id from publication_owners where auth_user_id='79000000-0000-4000-8000-000000000003');
set local role authenticated;
set local request.jwt.claims='{"role":"authenticated","sub":"79000000-0000-4000-8000-000000000003"}';
select is(api.publish_current_onboarding(null,null,'identity_only')->>'status','owner_not_eligible','Completed Owner without first-Publish receipt is not synthesized');
reset role;
select * from finish();
rollback;
