begin;
select no_plan();
select ok(not has_function_privilege('anon','api.resolve_public_identity(text)','EXECUTE'),'Public Identity transport remains withheld');
select ok(not has_function_privilege('authenticated','api.resolve_public_resource(text,bigint)','EXECUTE'),'Public Resource transport remains withheld');
select ok(not has_table_privilege('anon','core.identity_publications','SELECT'),'Anonymous raw publication reads denied');
select ok(not has_table_privilege('anon','core.spill_item_publications','SELECT'),'Anonymous raw Item reads denied');
grant execute on function api.resolve_public_identity(text) to anon, authenticated;
grant usage on schema api to anon;
grant execute on function api.resolve_public_resource(text,bigint) to anon, authenticated;
grant execute on function api.publish_current_onboarding(uuid,text,text) to authenticated;
insert into auth.users(id,email) values
 ('7a000000-0000-4000-8000-000000000001','public-one@example.test'),
 ('7a000000-0000-4000-8000-000000000002','public-two@example.test');
create temporary table public_test_owners as select auth_user_id,owner_id from core.owner_auth_bindings
 where auth_user_id in ('7a000000-0000-4000-8000-000000000001','7a000000-0000-4000-8000-000000000002');
set local role authenticated;
set local request.jwt.claims='{"role":"authenticated","sub":"7a000000-0000-4000-8000-000000000001"}';
select is(api.claim_current_owner_handle('public-one',1)->>'status','success','Claim public Handle');
select is(api.set_current_owner_primary_use_case('business',2)->>'status','success','Choose guidance');
select is(api.save_current_owner_basic_identity('Public Snapshot','Public biography',null,3)->>'status','success','Save Identity');
select is(api.save_current_owner_starter_composition('business',null,4)->>'status','success','Save layout');
select is(api.save_current_owner_resource_draft('menu','https://example.test/public-menu','Public Menu',null)->>'status','success','Save Resource');
select is(api.save_current_owner_identity_connection('generic_link',null,'https://example.test/public-link',null)->>'status','success','Save Connection');
select is(api.save_current_owner_product_draft('https://example.test/private-product','Private Product',null)->>'status','success','Retain private Product');
select is(api.advance_current_owner_relevant_first_job(5)->>'status','success','Reach S6');
select is(api.claim_current_owner_handle('public-renamed',6)->>'status','success','Protected alias retained after rename');
reset role;
insert into core.external_destination_safety(normalized_url,url_hash,safety_status,scanner_version,checked_at,expires_at) values
 ('https://example.test/public-menu',encode(extensions.digest('https://example.test/public-menu','sha256'),'hex'),'safe','public-read-test',now(),now()+interval '1 hour'),
 ('https://example.test/public-link',encode(extensions.digest('https://example.test/public-link','sha256'),'hex'),'safe','public-read-test',now(),now()+interval '1 hour');
set local role authenticated;
create temporary table public_review as select api.confirm_current_onboarding_preview(api.resolve_current_onboarding_preview()->>'snapshot_hash') as receipt;
select is(api.publish_current_onboarding((select (receipt->>'receipt_id')::uuid from public_review),(select receipt->>'snapshot_hash' from public_review),'resource')->>'status','success','Publish selected Resource atomically');
set local request.jwt.claims='{"role":"authenticated","sub":"7a000000-0000-4000-8000-000000000002"}';
select is(api.claim_current_owner_handle('public-two',1)->>'status','success','Other Owner has private Handle');
select is(api.set_current_owner_primary_use_case('personal',2)->>'status','success','Other guidance');
select is(api.save_current_owner_basic_identity('Private Other Owner',null,null,3)->>'status','success','Other Working remains private');
set local role anon;
set local request.jwt.claims='{"role":"anon"}';
select is(api.resolve_public_identity('public-renamed')->>'status','success','Anonymous visitor sees Published Identity');
select is(api.resolve_public_identity('public-renamed')->>'display_name','Public Snapshot','Only Published name');
select is(api.resolve_public_identity('PUBLIC-RENAMED'),api.resolve_public_identity('public-renamed'),'Case variant normalizes to same DTO');
select is(api.resolve_public_identity('public-one')->>'current_handle','public-renamed','Historical alias resolves same Owner and current canonical Handle');
select is(api.resolve_public_identity('public-renamed')->>'has_spill','true','Only safe Published Resource creates Spill availability');
select is(api.resolve_public_identity('public-renamed')->'connection'->>'available','true','Safe published Connection available');
select is(api.resolve_public_identity('public-renamed')->'connection'->>'destination_url','https://example.test/public-link','Exact safe URL permitted');
select ok(not (api.resolve_public_identity('public-renamed') ?| array['owner_id','receipt_id','profile_asset_key','identity_revision','product_draft']),'Private identity/receipt/revision/Draft fields absent');
select ok(api.resolve_public_identity('public-renamed')::text not like '%Private Product%','Unselected Product content absent');
select is(api.resolve_public_identity('public-two'),' {"status":"unavailable"}'::jsonb,'Unpublished known Owner uniformly unavailable');
select is(api.resolve_public_identity('unknown-owner'),api.resolve_public_identity('public-two'),'Unknown Owner does not disclose different state');
select is(api.resolve_public_identity('../public-renamed'),' {"status":"unavailable"}'::jsonb,'Path injection rejected');
select is(api.resolve_public_identity(' public-renamed'),' {"status":"unavailable"}'::jsonb,'Whitespace locator rejected');
select is(api.resolve_public_resource('public-renamed',1)->>'title','Public Menu','Published Resource title');
select is(api.resolve_public_resource('public-one',1)->>'current_handle','public-renamed','Resource alias uses canonical current Handle');
select is(api.resolve_public_resource('public-two',1),' {"status":"unavailable"}'::jsonb,'Owner-scoped reference cannot cross to published other Owner');
select is(api.resolve_public_resource('public-renamed',2),' {"status":"unavailable"}'::jsonb,'Reserved private Product reference remains unavailable');
select is(api.resolve_public_resource('public-renamed',0),' {"status":"unavailable"}'::jsonb,'Zero reference rejected');
select is(api.resolve_public_resource('public-renamed',9007199254740992),' {"status":"unavailable"}'::jsonb,'Unsafe integer reference rejected');
reset role;
update core.identity_working set display_name='Private edited Working',revision=revision+1
 where owner_id=(select owner_id from public_test_owners where auth_user_id='7a000000-0000-4000-8000-000000000001');
set local role authenticated;
set local request.jwt.claims='{"role":"authenticated","sub":"7a000000-0000-4000-8000-000000000002"}';
select is(api.resolve_public_identity('public-renamed')->>'display_name','Public Snapshot','Signed-in other Owner sees same Published snapshot after Working changes');
reset role;
update core.external_destination_safety set safety_status='blocked',reason_codes=array['malware'] where normalized_url='https://example.test/public-link';
set local role anon;
set local request.jwt.claims='{"role":"anon"}';
select is(api.resolve_public_identity('public-renamed')->'connection'->>'available','false','Later unsafe Connection visibly unavailable');
select is(api.resolve_public_identity('public-renamed')->'connection'->'destination_url','null'::jsonb,'Unsafe URL not exposed in public DTO');
reset role;
update core.external_destination_safety set expires_at=now()+interval '1 microsecond' where normalized_url='https://example.test/public-menu';
set local role anon;
select is(api.resolve_public_resource('public-renamed',1),' {"status":"unavailable"}'::jsonb,'Fresh clock rejects expired Resource despite transaction-time safe verdict');
select is(api.resolve_public_identity('public-renamed')->>'has_spill','false','Expired source does not create dead Spill CTA');
reset role;
update core.external_destination_safety set expires_at=now()+interval '1 hour' where normalized_url='https://example.test/public-menu';
update core.spill_item_publications set lifecycle_state='hidden' where owner_id=(select owner_id from public_test_owners where auth_user_id='7a000000-0000-4000-8000-000000000001');
set local role anon;
select is(api.resolve_public_resource('public-renamed',1),' {"status":"unavailable"}'::jsonb,'Hidden Resource unavailable');
select is(api.resolve_public_identity('public-renamed')->>'has_spill','false','Hidden Item excluded from Spill availability');
reset role;
update core.spill_item_publications set lifecycle_state='archived' where owner_id=(select owner_id from public_test_owners where auth_user_id='7a000000-0000-4000-8000-000000000001');
set local role anon;
select is(api.resolve_public_resource('public-renamed',1),' {"status":"unavailable"}'::jsonb,'Archived Resource unavailable');
reset role;
update core.identity_publications set lifecycle_state='hidden' where owner_id=(select owner_id from public_test_owners where auth_user_id='7a000000-0000-4000-8000-000000000001');
set local role anon;
select is(api.resolve_public_identity('public-renamed'),' {"status":"unavailable"}'::jsonb,'Hidden Identity uniformly unavailable');
reset role;
update core.identity_publications set lifecycle_state='published' where owner_id=(select owner_id from public_test_owners where auth_user_id='7a000000-0000-4000-8000-000000000001');
update core.owners set account_state='restricted' where id=(select owner_id from public_test_owners where auth_user_id='7a000000-0000-4000-8000-000000000001');
set local role anon;
select is(api.resolve_public_identity('public-renamed'),' {"status":"unavailable"}'::jsonb,'Restriction overrides published presence');
select is(api.resolve_public_identity('public-one'),' {"status":"unavailable"}'::jsonb,'Alias cannot disclose restricted account');
reset role;
update core.owners set account_state='suspended' where id=(select owner_id from public_test_owners where auth_user_id='7a000000-0000-4000-8000-000000000001');
set local role anon;
select is(api.resolve_public_resource('public-renamed',1),' {"status":"unavailable"}'::jsonb,'Suspension denies Resource through same Owner visibility gate');
reset role;
select * from finish();
rollback;
