import { z } from "zod";

import {
  PROFILE_MEDIA_CANONICAL_CONTENT_TYPE,
  PROFILE_MEDIA_CANONICAL_WEBP_QUALITY,
  PROFILE_MEDIA_MAX_CANONICAL_BYTES,
  PROFILE_MEDIA_MAX_CANONICAL_DIMENSION,
  PROFILE_MEDIA_MAX_CANONICAL_PIXELS,
  PROFILE_MEDIA_MAX_SOURCE_BYTES,
  PROFILE_MEDIA_MAX_SOURCE_DIMENSION,
  PROFILE_MEDIA_MAX_SOURCE_PIXELS,
  PROFILE_MEDIA_SOURCE_CONTENT_TYPES,
  type ProfileMediaSourceContentType,
} from "@spall-spill/profile-media-policy";

export {
  PROFILE_MEDIA_CANONICAL_CONTENT_TYPE,
  PROFILE_MEDIA_CANONICAL_WEBP_QUALITY,
  PROFILE_MEDIA_MAX_CANONICAL_BYTES,
  PROFILE_MEDIA_MAX_CANONICAL_DIMENSION,
  PROFILE_MEDIA_MAX_CANONICAL_PIXELS,
  PROFILE_MEDIA_MAX_SOURCE_BYTES,
  PROFILE_MEDIA_MAX_SOURCE_DIMENSION,
  PROFILE_MEDIA_MAX_SOURCE_PIXELS,
  PROFILE_MEDIA_SOURCE_CONTENT_TYPES,
  type ProfileMediaSourceContentType,
};

export const profileMediaSourceContentTypeSchema =
  z.enum(
    PROFILE_MEDIA_SOURCE_CONTENT_TYPES,
  );

export const PROFILE_MEDIA_PRESIGNED_PUT_TTL_SECONDS =
  300;

export const PROFILE_MEDIA_PRESIGNED_GET_TTL_SECONDS =
  300;

export const profileMediaDeclaredByteSizeSchema =
  z
    .number()
    .int()
    .min(1)
    .max(PROFILE_MEDIA_MAX_SOURCE_BYTES);

export const profileMediaAssetKeySchema =
  z.string().uuid();